
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniH.js
 */

#pragma once

#include <ReactCommon/TurboModule.h>
#include "RNOH/ArkTSTurboModule.h"


namespace rnoh {
    /**
     * JNI C++ class for module 'NativePushNotificationModule'
     */
    class JSI_EXPORT PushNotificationTurboModule : public ArkTSTurboModule {
    public:
        PushNotificationTurboModule(const ArkTSTurboModule::Context ctx, const std::string name);
    };
} // namespace rnoh
