
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJniCpp.js
 */

#include "PushNotificationTurboModule.h"
#include "RNOH/ArkTSTurboModule.h"

using namespace rnoh;
using namespace facebook;

static jsi::Value __hostFunction_PushNotificationTurboModule_removeAllDeliveredNotifications(
    jsi::Runtime &rt, 
    react::TurboModule &turboModule, 
    const jsi::Value *args, 
    size_t count) {
    return jsi::Value(static_cast<ArkTSTurboModule &>(turboModule).call(rt, "removeAllDeliveredNotifications", args, count));
}

static jsi::Value __hostFunction_PushNotificationTurboModule_removeDeliveredNotifications(
    jsi::Runtime &rt,
    react::TurboModule &turboModule,
    const jsi::Value *args,
    size_t count) {
    return jsi::Value(static_cast<ArkTSTurboModule &>(turboModule).call(rt, "removeDeliveredNotifications", args, count));
}

static jsi::Value __hostFunction_PushNotificationTurboModule_addNotificationRequest(
    jsi::Runtime &rt,
    react::TurboModule &turboModule,
    const jsi::Value *args,
    size_t count) {
    return jsi::Value(static_cast<ArkTSTurboModule &>(turboModule).call(rt, "addNotificationRequest", args, count));
}

static jsi::Value __hostFunction_PushNotificationTurboModule_setApplicationIconBadgeNumber(
    jsi::Runtime &rt,
    react::TurboModule &turboModule,
    const jsi::Value *args,
    size_t count) {
    return jsi::Value(static_cast<ArkTSTurboModule &>(turboModule).call(rt, "setApplicationIconBadgeNumber", args, count));
}

static jsi::Value __hostFunction_PushNotificationTurboModule_getDeliveredNotifications(
    jsi::Runtime &rt,
    react::TurboModule &turboModule,
    const jsi::Value *args,
    size_t count) {
    return jsi::Value(static_cast<ArkTSTurboModule &>(turboModule).call(rt, "getDeliveredNotifications", args, count));
}

PushNotificationTurboModule::PushNotificationTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
  : ArkTSTurboModule(ctx, name) {
  methodMap_["removeAllDeliveredNotifications"] = MethodMetadata {0, __hostFunction_PushNotificationTurboModule_removeAllDeliveredNotifications};
  methodMap_["removeDeliveredNotifications"] = MethodMetadata {1, __hostFunction_PushNotificationTurboModule_removeDeliveredNotifications};
  methodMap_["addNotificationRequest"] = MethodMetadata {1, __hostFunction_PushNotificationTurboModule_addNotificationRequest};
  methodMap_["setApplicationIconBadgeNumber"] = MethodMetadata {1, __hostFunction_PushNotificationTurboModule_setApplicationIconBadgeNumber};
  methodMap_["getDeliveredNotifications"] = MethodMetadata {1, __hostFunction_PushNotificationTurboModule_getDeliveredNotifications};
}
